services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://flick-api.lingon.cloud/api/v1
        VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY}
    container_name: flick-client
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true